import 'package:flutter/material.dart';

/// Single curated subject definition in Kortex's universal academic catalog.
class SubjectCatalogItem {
  const SubjectCatalogItem({
    required this.code,
    required this.title,
    required this.stream,
    required this.icon,
    required this.colorHex,
    this.materials = 30,
    this.coverage = 0.85,
    this.description = '',
  });

  final String code;
  final String title;
  final String stream; // 'Core', 'Sciences', 'Commercial', 'Arts', 'SAT Prep'
  final String icon;
  final String colorHex;
  final int materials;
  final double coverage;
  final String description;
}

/// Popular curriculum subject combination presets for 1-tap selection during calibration.
class SubjectCombinationPreset {
  const SubjectCombinationPreset({
    required this.id,
    required this.title,
    required this.subtitle,
    required this.icon,
    required this.colorHex,
    required this.subjectTitles,
  });

  final String id;
  final String title;
  final String subtitle;
  final IconData icon;
  final String colorHex;
  final List<String> subjectTitles;
}

/// Comprehensive subject catalog covering Nigerian (WAEC / JAMB / NECO)
/// and International (SAT / IGCSE) curriculum tracks.
const List<SubjectCatalogItem> kCuratedSubjectsCatalog = [
  // ── Core Subjects ────────────────────────────────────────────────────────
  SubjectCatalogItem(
    code: 'MTH',
    title: 'Mathematics',
    stream: 'Core',
    icon: 'calculate',
    colorHex: '#6366F1',
    materials: 48,
    coverage: 0.95,
    description: 'Algebra, Geometry, Trigonometry, Statistics & Probability',
  ),
  SubjectCatalogItem(
    code: 'ENG',
    title: 'English Language',
    stream: 'Core',
    icon: 'auto_stories',
    colorHex: '#F59E0B',
    materials: 52,
    coverage: 0.92,
    description: 'Comprehension, Summary, Lexis & Structure, Oral English',
  ),
  SubjectCatalogItem(
    code: 'CIV',
    title: 'Civic Education',
    stream: 'Core',
    icon: 'policy',
    colorHex: '#10B981',
    materials: 26,
    coverage: 0.88,
    description: 'Citizenship, Democratic Values, Human Rights & Duties',
  ),
  SubjectCatalogItem(
    code: 'DPR',
    title: 'Data Processing',
    stream: 'Core',
    icon: 'terminal',
    colorHex: '#8B5CF6',
    materials: 28,
    description: 'Data Management, Spreadsheets, Databases & Computer Ethics',
  ),
  SubjectCatalogItem(
    code: 'CMP',
    title: 'Computer Studies',
    stream: 'Core',
    icon: 'laptop',
    colorHex: '#06B6D4',
    coverage: 0.87,
    description: 'Hardware, Systems Architecture, Basic Programming & Logic',
  ),

  // ── Sciences Stream ──────────────────────────────────────────────────────
  SubjectCatalogItem(
    code: 'PHY',
    title: 'Physics',
    stream: 'Sciences',
    icon: 'bolt',
    colorHex: '#06B6D4',
    materials: 44,
    coverage: 0.90,
    description: 'Mechanics, Optics, Waves, Electromagnetism, Modern Physics',
  ),
  SubjectCatalogItem(
    code: 'CHM',
    title: 'Chemistry',
    stream: 'Sciences',
    icon: 'biotech',
    colorHex: '#EC4899',
    materials: 40,
    coverage: 0.89,
    description: 'Inorganic, Organic Reactions, Stoichiometry, Electrolysis',
  ),
  SubjectCatalogItem(
    code: 'BIO',
    title: 'Biology',
    stream: 'Sciences',
    icon: 'eco',
    colorHex: '#10B981',
    materials: 46,
    coverage: 0.91,
    description: 'Cell Structure, Genetics, Ecology, Human Physiology',
  ),
  SubjectCatalogItem(
    code: 'FMTH',
    title: 'Further Mathematics',
    stream: 'Sciences',
    icon: 'functions',
    colorHex: '#4F46E5',
    materials: 35,
    description: 'Calculus, Vectors, Matrices, Mechanics & Pure Math',
  ),
  SubjectCatalogItem(
    code: 'AGR',
    title: 'Agricultural Science',
    stream: 'Sciences',
    icon: 'agriculture',
    colorHex: '#84CC16',
    materials: 29,
    coverage: 0.86,
    description: 'Soil Science, Crop Production, Animal Nutrition & Farm Tools',
  ),
  SubjectCatalogItem(
    code: 'TD',
    title: 'Technical Drawing',
    stream: 'Sciences',
    icon: 'architecture',
    colorHex: '#F97316',
    materials: 24,
    coverage: 0.82,
    description: 'Orthographic Projections, Isometric Drafting & Geometric Curves',
  ),
  SubjectCatalogItem(
    code: 'ANH',
    title: 'Animal Husbandry',
    stream: 'Sciences',
    icon: 'pets',
    colorHex: '#A855F7',
    materials: 25,
    coverage: 0.84,
    description: 'Livestock Management, Animal Health, Breeding & Processing',
  ),
  SubjectCatalogItem(
    code: 'PHE',
    title: 'Physical Education',
    stream: 'Sciences',
    icon: 'fitness_center',
    colorHex: '#14B8A6',
    materials: 22,
    coverage: 0.80,
    description: 'Anatomy, Sports Psychology, First Aid & Athletic Rules',
  ),

  // ── Commercial Stream ────────────────────────────────────────────────────
  SubjectCatalogItem(
    code: 'ECN',
    title: 'Economics',
    stream: 'Commercial',
    icon: 'trending_up',
    colorHex: '#3B82F6',
    materials: 38,
    coverage: 0.87,
    description: 'Micro & Macro Economics, Demand, Supply, Public Finance',
  ),
  SubjectCatalogItem(
    code: 'COM',
    title: 'Commerce',
    stream: 'Commercial',
    icon: 'storefront',
    colorHex: '#0284C7',
    coverage: 0.82,
    description: 'Trade, Banking, Insurance, Transport, Warehousing & E-commerce',
  ),
  SubjectCatalogItem(
    code: 'ACC',
    title: 'Financial Accounting',
    stream: 'Commercial',
    icon: 'receipt_long',
    colorHex: '#2563EB',
    materials: 34,
    coverage: 0.84,
    description: 'Final Accounts, Balance Sheet, Ledger, Depreciation & Ratios',
  ),
  SubjectCatalogItem(
    code: 'BKP',
    title: 'Book Keeping',
    stream: 'Commercial',
    icon: 'menu_book',
    colorHex: '#0D9488',
    materials: 26,
    coverage: 0.81,
    description: 'Double-entry, Cash Book, Petty Cash & Journal Entries',
  ),
  SubjectCatalogItem(
    code: 'MKT',
    title: 'Marketing',
    stream: 'Commercial',
    icon: 'campaign',
    colorHex: '#E11D48',
    materials: 27,
    coverage: 0.83,
    description: 'Market Research, Pricing, Distribution & Consumer Behavior',
  ),
  SubjectCatalogItem(
    code: 'INS',
    title: 'Insurance',
    stream: 'Commercial',
    icon: 'shield',
    colorHex: '#6D28D9',
    materials: 24,
    coverage: 0.80,
    description: 'Risk Management, Underwriting, Life & Non-life Policies',
  ),
  SubjectCatalogItem(
    code: 'OFP',
    title: 'Office Practice',
    stream: 'Commercial',
    icon: 'business_center',
    colorHex: '#475569',
    materials: 22,
    coverage: 0.79,
    description: 'Administrative Procedures, Filing, Business Communication',
  ),

  // ── Arts & Humanities Stream ─────────────────────────────────────────────
  SubjectCatalogItem(
    code: 'LIT',
    title: 'Literature in English',
    stream: 'Arts',
    icon: 'menu_book',
    colorHex: '#D97706',
    materials: 36,
    coverage: 0.89,
    description: 'African & Non-African Prose, Poetry, Drama & Literary Criticism',
  ),
  SubjectCatalogItem(
    code: 'GOV',
    title: 'Government',
    stream: 'Arts',
    icon: 'account_balance',
    colorHex: '#8B5CF6',
    materials: 32,
    coverage: 0.86,
    description: 'Political Systems, Constitutions, Electoral Process, Foreign Policy',
  ),
  SubjectCatalogItem(
    code: 'GEO',
    title: 'Geography',
    stream: 'Arts',
    icon: 'public',
    colorHex: '#0D9488',
    materials: 28,
    coverage: 0.80,
    description: 'Physical Geography, Climatology, Map Reading, Regional Studies',
  ),
  SubjectCatalogItem(
    code: 'HIS',
    title: 'History',
    stream: 'Arts',
    icon: 'history_edu',
    colorHex: '#78350F',
    materials: 25,
    coverage: 0.82,
    description: 'West African Kingdoms, Nigerian History, Colonial Era & World Wars',
  ),
  SubjectCatalogItem(
    code: 'CRK',
    title: 'Christian Religious Knowledge (CRK)',
    stream: 'Arts',
    icon: 'church',
    colorHex: '#B45309',
    materials: 29,
    description: 'Old & New Testament, Christian Ethics, Apostles & Early Church',
  ),
  SubjectCatalogItem(
    code: 'IRK',
    title: 'Islamic Religious Knowledge (IRK)',
    stream: 'Arts',
    icon: 'mosque',
    colorHex: '#047857',
    materials: 29,
    description: 'Quran Studies, Hadith, Fiqh, Islamic History & Pillars of Faith',
  ),
  SubjectCatalogItem(
    code: 'FRE',
    title: 'French',
    stream: 'Arts',
    icon: 'translate',
    colorHex: '#3B82F6',
    materials: 26,
    coverage: 0.81,
    description: 'Grammar, Reading Comprehension, Oral Conversation & Writing',
  ),
  SubjectCatalogItem(
    code: 'YOR',
    title: 'Yoruba',
    stream: 'Arts',
    icon: 'language',
    colorHex: '#EA580C',
    materials: 24,
    coverage: 0.80,
    description: 'Awon Asa, Ewi, Itan, Akoto & Onka Yoruba',
  ),
  SubjectCatalogItem(
    code: 'IGB',
    title: 'Igbo',
    stream: 'Arts',
    icon: 'language',
    colorHex: '#16A34A',
    materials: 24,
    coverage: 0.80,
    description: 'Omenala, Abu, Agumagu & Nsupe Igbo',
  ),
  SubjectCatalogItem(
    code: 'HAU',
    title: 'Hausa',
    stream: 'Arts',
    icon: 'language',
    colorHex: '#9333EA',
    materials: 24,
    coverage: 0.80,
    description: "Al'adun Hausawa, Rubutu, Adabi & Nahawun Hausa",
  ),
  SubjectCatalogItem(
    code: 'ARA',
    title: 'Arabic',
    stream: 'Arts',
    icon: 'translate',
    colorHex: '#059669',
    materials: 22,
    coverage: 0.78,
    description: 'Arabic Grammar, Classical Texts, Comprehension & Composition',
  ),
  SubjectCatalogItem(
    code: 'ART',
    title: 'Visual Arts',
    stream: 'Arts',
    icon: 'palette',
    colorHex: '#BE185D',
    materials: 25,
    coverage: 0.83,
    description: 'Art History, Painting, Sculpture, Graphics & African Crafts',
  ),
  SubjectCatalogItem(
    code: 'MUS',
    title: 'Music',
    stream: 'Arts',
    icon: 'music_note',
    colorHex: '#6366F1',
    materials: 23,
    coverage: 0.80,
    description: 'Rudiments of Music, Western Harmony, African Rhythms & Ear Training',
  ),
  SubjectCatalogItem(
    code: 'FDN',
    title: 'Food and Nutrition',
    stream: 'Arts',
    icon: 'restaurant',
    colorHex: '#E11D48',
    materials: 26,
    coverage: 0.82,
    description: 'Nutritional Science, Food Chemistry, Meal Planning & Preservation',
  ),

  // ── SAT & International Prep ─────────────────────────────────────────────
  SubjectCatalogItem(
    code: 'SAT-RC',
    title: 'SAT Reading Comprehension',
    stream: 'SAT Prep',
    icon: 'auto_stories',
    colorHex: '#F59E0B',
    materials: 38,
    coverage: 0.92,
    description: 'Passage analysis, textual evidence, central ideas & rhetoric',
  ),
  SubjectCatalogItem(
    code: 'SAT-WL',
    title: 'SAT Writing & Language',
    stream: 'SAT Prep',
    icon: 'menu_book',
    colorHex: '#EC4899',
    materials: 32,
    coverage: 0.90,
    description: 'Standard English conventions, expression of ideas & sentence structure',
  ),
  SubjectCatalogItem(
    code: 'SAT-M1',
    title: 'SAT Math: Heart of Algebra',
    stream: 'SAT Prep',
    icon: 'calculate',
    colorHex: '#6366F1',
    materials: 35,
    coverage: 0.90,
    description: 'Linear equations, systems, inequalities & function models',
  ),
  SubjectCatalogItem(
    code: 'SAT-M2',
    title: 'SAT Math: Advanced & Problem Solving',
    stream: 'SAT Prep',
    icon: 'functions',
    colorHex: '#8B5CF6',
    materials: 36,
    coverage: 0.88,
    description: 'Nonlinear functions, quadratics, ratios, rates & data analysis',
  ),
];

/// Curated quick-select subject combination presets for West African and international students.
const List<SubjectCombinationPreset> kCuratedSubjectPresets = [
  SubjectCombinationPreset(
    id: 'science_premed',
    title: '🔬 Science / Pre-Med',
    subtitle: 'Math, English, Physics, Chem, Bio',
    icon: Icons.biotech_rounded,
    colorHex: '#10B981',
    subjectTitles: [
      'Mathematics',
      'English Language',
      'Physics',
      'Chemistry',
      'Biology',
    ],
  ),
  SubjectCombinationPreset(
    id: 'engineering_tech',
    title: '⚙️ Engineering & Tech',
    subtitle: 'Math, English, Further Math, Physics, Chem',
    icon: Icons.precision_manufacturing_rounded,
    colorHex: '#6366F1',
    subjectTitles: [
      'Mathematics',
      'English Language',
      'Further Mathematics',
      'Physics',
      'Chemistry',
      'Computer Studies',
    ],
  ),
  SubjectCombinationPreset(
    id: 'commercial_business',
    title: '📊 Commercial & Finance',
    subtitle: 'Math, English, Economics, Accounts, Commerce',
    icon: Icons.trending_up_rounded,
    colorHex: '#3B82F6',
    subjectTitles: [
      'Mathematics',
      'English Language',
      'Economics',
      'Financial Accounting',
      'Commerce',
      'Government',
    ],
  ),
  SubjectCombinationPreset(
    id: 'arts_law',
    title: '⚖️ Arts & Law',
    subtitle: 'Math, English, Literature, Government, CRK',
    icon: Icons.gavel_rounded,
    colorHex: '#D97706',
    subjectTitles: [
      'Mathematics',
      'English Language',
      'Literature in English',
      'Government',
      'Christian Religious Knowledge (CRK)',
    ],
  ),
  SubjectCombinationPreset(
    id: 'sat_standard',
    title: '🇺🇸 SAT Digital Standard',
    subtitle: 'Reading, Writing & Digital Math',
    icon: Icons.school_rounded,
    colorHex: '#8B5CF6',
    subjectTitles: [
      'SAT Reading Comprehension',
      'SAT Writing & Language',
      'SAT Math: Heart of Algebra',
      'SAT Math: Advanced & Problem Solving',
    ],
  ),
];
