// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy0raUCON8Q64uS_ybbnjZAR47Ieb14es',
    appId: '1:1073532728398:web:8362216c490832a0897f1f',
    messagingSenderId: '1073532728398',
    projectId: 'kortex-study-app-2026',
    authDomain: 'kortex-study-app-2026.firebaseapp.com',
    storageBucket: 'kortex-study-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLsd8f8GLCK8oSp5IXVlCxY9RPxjNXxoE',
    appId: '1:1073532728398:android:369b70aab8c09b90897f1f',
    messagingSenderId: '1073532728398',
    projectId: 'kortex-study-app-2026',
    storageBucket: 'kortex-study-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtO8gdhr99AEzJdf2-k_rXA5omSa22-n0',
    appId: '1:1073532728398:ios:e50651b1d7649388897f1f',
    messagingSenderId: '1073532728398',
    projectId: 'kortex-study-app-2026',
    storageBucket: 'kortex-study-app-2026.firebasestorage.app',
    iosBundleId: 'com.kortexify.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtO8gdhr99AEzJdf2-k_rXA5omSa22-n0',
    appId: '1:1073532728398:ios:e50651b1d7649388897f1f',
    messagingSenderId: '1073532728398',
    projectId: 'kortex-study-app-2026',
    storageBucket: 'kortex-study-app-2026.firebasestorage.app',
    iosBundleId: 'com.kortexify.app',
  );
}
