/// Pure, testable text preprocessor that sanitizes and formats Syllabot AI responses
/// into clean, standard-compliant Markdown and LaTeX before visual rendering.
///
/// Features:
/// - Strips reasoning tokens (`<think>...</think>`), prompt leakage (`<|im_start|>`, etc.), and garbage control characters.
/// - Converts LaTeX display delimiters `\[...\]` into standard `$$...$$` blocks.
/// - Converts LaTeX inline delimiters `\(...\)` into standard `$...$` inline math.
/// - Identifies parenthesized/bracketed LaTeX expressions (e.g. `(1.0\ \text{m/s}^2)`, `(2\ \Omega)`, `(500\ \text{Hz})`)
///   and converts them to proper `$1.0\ \text{m/s}^2$`, `$2\ \Omega$`, `$500\ \text{Hz}$` equations.
/// - Wraps bare LaTeX commands (e.g. `\frac`, `\sqrt`, `\Omega`) that appear outside math delimiters in `$...$`.
/// - Normalizes escaped spaces `\ ` and whitespace within LaTeX tokens.
class SyllabotResponseFormatter {
  const SyllabotResponseFormatter._();

  static final RegExp _thinkingTagsRegex = RegExp(
    r'<think>[\s\S]*?<\/think>|<\/?think>|<\|[a-zA-Z0-9_\-]+\|>',
    caseSensitive: false,
  );

  static final RegExp _invisibleCharsRegex = RegExp(
    r'[\u200B-\u200D\uFEFF\u200E\u200F\u2028\u2029\u2060\u00AD]',
  );

  static final RegExp _controlCharsRegex = RegExp(
    r'[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]',
  );

  static final RegExp _latexBlockDelimiterRegex = RegExp(
    r'\\\[([\s\S]*?)\\\]',
  );

  static final RegExp _latexInlineDelimiterRegex = RegExp(
    r'\\\(([\s\S]*?)\\\)',
  );

  /// Captures expressions enclosed in parentheses that contain LaTeX commands or backslash escapes,
  /// such as `(1.0\ \text{m/s}^2)`, `(2\ \Omega)`, `(500\ \text{Hz})`, `(0.68\ \text{m})`, `(340\ \text{m/s})`.
  static final RegExp _parenthesizedLatexRegex = RegExp(
    r'\(([^)\n]*?\\{1,2}[a-zA-Z]+(?:\{[^{}]*\})*[^)\n]*?)\)|\(([^)\n]*?\\{1,2}[ ]+[^)\n]*?)\)',
  );

  /// Captures expressions enclosed in square brackets that contain LaTeX commands.
  static final RegExp _bracketedLatexRegex = RegExp(
    r'\[([^\]\n]*?\\{1,2}[a-zA-Z]+(?:\{[^{}]*\})*[^\]\n]*?)\]',
  );

  /// Captures bare numbers accompanied by LaTeX commands/units (e.g. `2\ \Omega`, `500\ \text{Hz}`, `1.0\ \text{m/s}^2`).
  static final RegExp _bareNumberWithLatexRegex = RegExp(
    r'(?<!\$|\\)\b(\d+(?:\.\d+)?\s*(?:\\{1,2}\s*)?\\{1,2}(?:Omega|text\{[^{}]*\}|mu|micro|degree|circ|pm|times|alpha|beta|gamma|theta|lambda|pi)(?:(?:\^|_)(?:\{[^{}]*\}|[a-zA-Z0-9]))*)(?!\$)',
  );

  /// Known LaTeX commands to detect bare math expressions outside delimiters.
  static final RegExp _bareLatexCmdRegex = RegExp(
    r'(?<!\$|\\)(\\{1,2}(?:frac|sqrt|alpha|beta|gamma|theta|pi|pm|mp|times|div|le|ge|neq|approx|infty|circ|partial|sum|int|oint|to|rightarrow|leftarrow|leftrightarrow|mathrm|mathbf|mathit|textbf|text|mathbb|mathcal|lambda|mu|sigma|omega|Delta|Omega|Theta|Lambda|Sigma|Phi|Psi|cdot|cos|sin|tan|cot|sec|csc|log|ln|deg|vec|hat|bar|tilde|dot|ddot)(?:\{[^{}]*(?:\{[^{}]*\}[^{}]*)*\}|\[[^\]]*\])*(?:(?:\^|_)(?:\{[^{}]*\}|[a-zA-Z0-9]))*)(?!\$)',
  );

  /// Formats raw text generated by Syllabot AI into clean Markdown and standard LaTeX delimiters.
  static String format(String rawText) {
    if (rawText.trim().isEmpty) return '';

    var text = rawText;

    // 1. Strip reasoning tags, model prompt artifacts, and invisible tokens
    text = text
        .replaceAll(_thinkingTagsRegex, '')
        .replaceAll(_controlCharsRegex, '')
        .replaceAll(_invisibleCharsRegex, '');

    // 2. Normalize accidental double-backslashes in JSON (e.g. \\text or \\Omega)
    text = text.replaceAllMapped(
      RegExp(r'\\\\([a-zA-Z]+|[ ])'),
      (m) => '\\${m[1]}',
    );

    // 2. Decode common HTML entities so they do not leak as raw strings
    text = text
        .replaceAll('&quot;', '"')
        .replaceAll('&apos;', "'")
        .replaceAll('&#39;', "'")
        .replaceAll('&#039;', "'")
        .replaceAll('&amp;', '&')
        .replaceAll('&lt;', '<')
        .replaceAll('&gt;', '>')
        .replaceAll('&nbsp;', ' ');

    // 3. Normalize LaTeX display delimiters \[ ... \] -> $$ ... $$
    text = text.replaceAllMapped(_latexBlockDelimiterRegex, (m) {
      final formula = m[1]?.trim() ?? '';
      return '\n\n\$\$$formula\$\$\n\n';
    });

    // 4. Normalize LaTeX inline delimiters \( ... \) -> $ ... $
    text = text.replaceAllMapped(_latexInlineDelimiterRegex, (m) {
      final formula = m[1]?.trim() ?? '';
      return '\$$formula\$';
    });

    // 5. Convert parenthesized LaTeX expressions e.g. `(1.0\ \text{m/s}^2)` or `(2\ \Omega)` to `$1.0\ \text{m/s}^2$`
    text = text.replaceAllMapped(_parenthesizedLatexRegex, (m) {
      final expr = (m[1] ?? m[2])?.trim() ?? '';
      if (expr.isEmpty) return m[0]!;
      return '\$$expr\$';
    });

    // 6. Convert bracketed LaTeX expressions e.g. `[2\ \Omega]` to `$2\ \Omega$`
    text = text.replaceAllMapped(_bracketedLatexRegex, (m) {
      final expr = m[1]?.trim() ?? '';
      if (expr.isEmpty) return m[0]!;
      return '\$$expr\$';
    });

    // 7. Protect code blocks before bare command conversion
    final codeBlocks = <String>[];
    text = text.replaceAllMapped(
      RegExp(r'```[\s\S]*?```|`[^`\n]+`'),
      (m) {
        final idx = codeBlocks.length;
        codeBlocks.add(m[0]!);
        return '%%SYLLABOT_CODE_$idx%%';
      },
    );

    // 8. Protect already-delimited math blocks ($$...$$ and $...$)
    final mathBlocks = <String>[];
    String protectMath(String input) {
      return input.replaceAllMapped(
        RegExp(r'\$\$[\s\S]*?\$\$|(?<!\\)\$(?!\s)((?:\\.|[^\$\n])+?)(?<!\s)\$'),
        (m) {
          final idx = mathBlocks.length;
          mathBlocks.add(m[0]!);
          return '%%SYLLABOT_MATH_$idx%%';
        },
      );
    }

    text = protectMath(text);

    // 9. Convert remaining bare numbers with LaTeX units/commands (e.g. `2\ \Omega`, `500\ \text{Hz}`) to `$...$`
    text = text.replaceAllMapped(_bareNumberWithLatexRegex, (m) {
      final expr = m[1]?.trim() ?? '';
      if (expr.isEmpty) return m[0]!;
      return '\$$expr\$';
    });

    // Protect newly delimited math from bare command replacement
    text = protectMath(text);

    // 10. Wrap any remaining bare LaTeX commands found in normal sentences
    text = text.replaceAllMapped(_bareLatexCmdRegex, (m) {
      final cmd = m.group(1)?.trim() ?? '';
      if (cmd.isEmpty) return '';
      return '\$$cmd\$';
    });

    // 11. Restore protected math blocks
    for (var i = 0; i < mathBlocks.length; i++) {
      text = text.replaceAll('%%SYLLABOT_MATH_$i%%', mathBlocks[i]);
    }

    // 12. Restore protected code blocks
    for (var i = 0; i < codeBlocks.length; i++) {
      text = text.replaceAll('%%SYLLABOT_CODE_$i%%', codeBlocks[i]);
    }

    return text.trim();
  }
}
